/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.hmellema.smithy.rust.test;

import java.io.FileWriter;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Path;
import java.util.logging.Logger;
import software.amazon.smithy.build.PluginContext;
import software.amazon.smithy.build.SmithyBuildPlugin;

public final class TestRustCodegenPlugin implements SmithyBuildPlugin {
    private static final Logger LOGGER = Logger.getLogger(TestRustCodegenPlugin.class.getName());

    @Override
    public String getName() {
        return "test-rust-codegen";
    }

    @Override
    public void execute(PluginContext context) {
        LOGGER.info("Executing codegen");
        write(context, "demo.rs", """
        pub struct Rectangle {
            pub width: u32,
            pub height: u32,
        }
        """);
        write(context, "other.rs", """
        pub struct Generated {
            pub a: u32
        }
        """);
        LOGGER.info("Codegen complete");
    }

    private static final void write(PluginContext context, String path, String data) {
        var file = context.getFileManifest().addFile(Path.of(path));
        try (var writer = new FileWriter(file.toFile())) {
            writer.append(data);
        } catch (IOException ioException) {
            throw new UncheckedIOException(ioException);
        }
    }
}
