/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dev.hmellema.smithy.rust.test;

import java.io.FileWriter;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Path;
import java.util.logging.Logger;
import software.amazon.smithy.build.PluginContext;
import software.amazon.smithy.build.SmithyBuildPlugin;

public final class TestRustCodegenPlugin implements SmithyBuildPlugin {
    private static final Logger LOGGER = Logger.getLogger(TestRustCodegenPlugin.class.getName());

    @Override
    public String getName() {
        return "test-rust-codegen";
    }

    @Override
    public void execute(PluginContext context) {
        LOGGER.info("Executing codegen");
        // TODO: Actually depend on the shapes a bit
        var file = context.getFileManifest().addFile(Path.of("demo.rs"));
        try (var writer = new FileWriter(file.toFile())) {
            writer.append("""
                    pub struct Rectangle {
                        width: u32,
                        height: u32,
                    }
                    """);
        } catch (IOException ioException) {
            throw new UncheckedIOException(ioException);
        }
        LOGGER.info("Codegen complete");
    }
}
