[package]
name = "test-crate"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
smithy-cargo = "0.1.0"
crabtime = "1.1.1"
walkdir = "2.5.0"

[build-dependencies]
smithy-cargo = "0.1.0"
walkdir = "2.5.0"

[patch.crates-io]
smithy-cargo = { path = ".." }
