name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and test project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Smithy CLI
        run: |
          mkdir -p /tmp/smithy-install/smithy
          curl -L https://github.com/smithy-lang/smithy/releases/latest/download/smithy-cli-linux-x86_64.zip -o /tmp/smithy-install/smithy-cli-linux-x86_64.zip
          unzip -qo /tmp/smithy-install/smithy-cli-linux-x86_64.zip -d /tmp/smithy-install
          mv /tmp/smithy-install/smithy-cli-linux-x86_64/* /tmp/smithy-install/smithy
          sudo /tmp/smithy-install/smithy/install

      - name: Run build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
